CREATE TABLE produto(
	id SERIAL PRIMARY KEY NOT NULL, 
	descricao CHARACTER VARYING(250) NOT NULL,
	preco_unitario DOUBLE PRECISION NOT NULL
);
CREATE TABLE cliente(
	id SERIAL PRIMARY KEY NOT NULL, 
	nome CHARACTER VARYING(250) NOT NULL,
	cpf CHARACTER VARYING(12) NOT NULL
);
